language: cpp
dist: xenial
services:
  - docker
before_install:
  - ./scripts/build/tool-build.sh date
sudo: true
script: 
  - git submodule update --init --recursive
  - ./scripts/build/using_docker.sh
notifications:
  email: false
